export const products = [
    /* Necklaces: Id: 1-8 */
    { id: 1, 
        name: "Circle Pendant Necklace", 
        title: "Circle-Pendant",
        price: 42, 
        description: "14mm charm, 27mm chain",
        image: "../../assets/images/NECKLACES-CHAINS/Circle Pendant/Customizable Circle Pendant/m1.jpg"},
    { id:2, 
        name: "Bar Pendant Necklace", 
        title: "Bar-Pendant",
        price:44, 
        description: " 5mm width, 22 inches length/customizable",
        image: "../../assets/images/NECKLACES-CHAINS/Bar Pendant/bar_mirror_1.jpeg"},
    { id:3, 
        name: "Lock Pendant Necklace", 
        title: "Lock-Pendant",
        price:48, 
        description: "Customizable up to 4 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES-CHAINS/Lock Pendant/lock_3.jpeg"},
    { id:4, 
        name: "Heart Pendant Necklace", 
        title: "Heart-Pendant",
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES-CHAINS//Heart Pendant/heart_1.jpeg"},
    { id:5, 
        name: "Mini Circle Pendant Necklace", 
        title: "Mini-Circle-Pendant",
        price:45, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES-CHAINS//Mini Circle Pendants/minicircle_1.jpeg"},
    { id:6, 
        name: "Unisex Drip Chain Necklace", 
        title: "Unisex-Drip-Chain",
        price:45, 
        description: "Customizable up to 6 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES-CHAINS/Unisex Drip Chain/chain_3.jpeg"},
    { id:7, 
        name: "Circle Butterfly Pendant Necklace", 
        title: "Circle-Butterfly-Pendant-Necklace",
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES-CHAINS/Circle Pendant/Butterfly Circle Pendant/b1.jpg"},
  /*
    { id: 8,
        name: "Circle Butterfly Pendant Necklace",
        price:42,
        description: "A butterfly necklace to remind yourself that you will soar when you are unapologetically you!",
        image: ""},
    /*
    { id: 9,
        name: "Circle Sun Pendant Necklace",
        price:42,
        description: "A butterfly necklace to remind yourself that you will soar when you are unapologetically you!",
        image: ""},
    
    /* Earrings: Id: 10-16 */
      { id:10, 
        name: "Dangle Earrings With Ball Charms Earrings", 
        title: "Dangle-Earrings",
        price: 27, 
        description: "",
        image: "../../assets/images/EARRINGS/Dangle Earrings with Ball Charm/dangle_1.jpeg"},
      { id:11, 
        name: "Gold Closed Circle Charm Earrings", 
        title: "Gold-Closed-Circle-Charm",
        price: 27, 
        description: "",
        image: "../../assets/images/EARRINGS/Gold Round Charm/goldroundcharm_1.jpeg"},
      { id:12, 
        name: "Butterfly Charm Earrings", 
        title: "Butterfly-Charm",
        price: 28, 
        description: "",
        image: "../../assets/images/EARRINGS/Butterfly Earrings/butterfly_1.jpeg"},
      { id:13, 
        name: "Small Hoop With Ball Charm Earrings", 
        title: "Small-Hoop",
        price: 24, 
        description: "",
        image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
      { id:14, 
        name: "Freshwater Pearl Dangle Earrings", 
        title: "Freshwater-Pearl-Dangle",
        price: 30, 
        description: "",
        image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
      { id:15, 
        name: "Gold Saturn With/without Pearl Earrings", 
        title: "Gold-Saturn",
        price:28, 
        description: "",
        image: "../../assets/images/EARRINGS/Saturn Earrings/saturn_1.jpeg"},  
      { id:16, 
        name: "Shooting Star Earrings", 
        title: "Shooting-Star",
        price:28, 
        description: "",
        image: "../../assets/images/EARRINGS/Star Earrings/star_1.jpeg"},



  ]