export const earrings = [
    /* Necklaces: Id: 1-7 */
  { id: 1, 
    name: "Handmade Dangle Earrings With Ball Charms Earrings, 24k Gold Charms · Personalized Gift", 
    price: 27, 
    description: "",
    image: "../../assets/images/EARRINGS/Small Hoops With Ball/smallhoops_1.jpeg"},
  { id:2, 
    name: "Handmade Gold Closed Circle Charm Earrings, 24k Gold Charms · Personalized Gift", 
    price: 27, 
    description: "",
    image: "../../assets/images/EARRINGS/Gold Round Charm/goldroundcharm_1.jpeg"},
  { id:3, 
    name: "Handmade Butterfly Charm Earrings, 18k Gold Charms · Personalized Gift", 
    price: 28, 
    description: "",
    image: "../../assets/images/EARRINGS/Butterfly Earrings/butterfly_1.jpeg"},
  { id:4, 
    name: "Handmade Small Hoop With Ball Charm Earrings, 24k Gold Charms · Personalized Gift", 
    price: 24, 
    description: "",
    image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
  { id:5, 
    name: "Handmade Freshwater Pearl Dangle Earrings, Removable Chain, 18k Gold Chain · Personalized Gift", 
    price: 30, 
    description: "",
    image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
  { id:6, 
    name: "Handmade Gold Saturn With/without Pearl Earrings, 18k/24k Gold Charms · Personalized Gift", 
    price:28, 
    description: "",
    image: "../../assets/images/EARRINGS/Saturn Earrings/saturn_1.jpeg"},  
  { id:7, 
    name: "Handmade Shooting Star Earrings, 24k Gold Charms · Personalized Gift", 
    price:28, 
    description: "",
    image: "../../assets/images/EARRINGS/Star Earrings/star_1.jpeg"},

  ]