export const earrings = [
    /* Necklaces: Id: 1-7 */
  { id: 1, 
    name: "Handmade Dangle Earrings With Ball Charms Earrings, 24k Gold Charms · Personalized Gift", 
    price: 27, 
    description: "",
    image: "../../assets/images/EARRINGS/Small Hoops With Ball/smallhoops_1.jpeg"},
  { id:2, 
    name: "Handmade Gold Closed Circle Charm Earrings, 24k Gold Charms · Personalized Gift", 
    price:44, 
    description: "",
    image: "../../assets/images/EARRINGS/Gold Round Charm/goldroundcharm_1.jpeg"},
  { id:3, 
    name: "Handmade Butterfly Charm Earrings, 18k Gold Charms · Personalized Gift", 
    price:48, 
    description: "",
    image: "../../assets/images/EARRINGS/Butterfly Earrings/butterfly_1.jpeg"},
  { id:4, 
    name: "Handmade Freshwater Pearl Dangle Earrings, Removable Chain, 18k Gold Chain · Personalized Gift", 
    price:45, 
    description: "",
    image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
  { id:5, 
    name: "Heart Pendant", 
    price:42, 
    description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
    image: "../../assets/images/NECKLACES/Heart Pendant/heart_1.jpeg"},
  { id:6, 
    name: "Mini Circle Pendant", 
    price:45, 
    description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
    image: "../../assets/images/NECKLACES/Mini Circle Pendants/minicircle_1.jpeg"},      
  { id:7, 
    name: "Gold Coin Chain Choker", 
    price:42, 
    description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
    image: ""},
  { id: 8,
    name: "Handmade Circle Butterfly Pendant Necklace, 18k Gold-Filled · Personalized Gift",
    price:42,
    description: "A butterfly necklace to remind yourself that you will soar when you are unapologetically you!"}


  ]