export const products = [
    /* Necklaces: Id: 1-8 */
    { id: 1, 
        name: "Handmade and Customizable Circle Pendant Necklace, 18k Gold-Filled · Personalized Gift", 
        price: 42, 
        description: "14mm charm, 27mm chain",
        image: "../../assets/images/NECKLACES/Circle Pendant/circle_1.jpeg"},
    { id:2, 
        name: "Bar Pendant", 
        price:44, 
        description: " 5mm width, 22 inches length/customizable",
        image: "../../assets/images/NECKLACES/Bar Pendant/bar_1.jpeg"},
    { id:3, 
        name: "Lock Pendant", 
        price:48, 
        description: "Customizable up to 4 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Lock Pendant/lock_1.jpeg"},
    { id:4, 
        name: "Unisex Drip Chain", 
        price:45, 
        description: "Customizable up to 6 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Unisex Drip Chain/chain_1.jpeg"},
    { id:5, 
        name: "Heart Pendant", 
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Heart Pendant/heart_1.jpeg"},
    { id:6, 
        name: "Mini Circle Pendant", 
        price:45, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Mini Circle Pendants/minicircle_1.jpeg"},      
    { id:7, 
        name: "Gold Coin Chain Choker", 
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: ""},
    { id: 8,
        name: "Handmade Circle Butterfly Pendant Necklace, 18k Gold-Filled · Personalized Gift",
        price:42,
        description: "A butterfly necklace to remind yourself that you will soar when you are unapologetically you!",
        image: ""},
    /* Earrings: Id: 9-15 */
    { id: 9, 
        name: "Handmade Dangle Earrings With Ball Charms Earrings, 24k Gold Charms · Personalized Gift", 
        price: 27, 
        description: "",
        image: "../../assets/images/EARRINGS/Small Hoops With Ball/smallhoops_1.jpeg"},
      { id:10, 
        name: "Handmade Gold Closed Circle Charm Earrings, 24k Gold Charms · Personalized Gift", 
        price: 27, 
        description: "",
        image: "../../assets/images/EARRINGS/Gold Round Charm/goldroundcharm_1.jpeg"},
      { id:11, 
        name: "Handmade Butterfly Charm Earrings, 18k Gold Charms · Personalized Gift", 
        price: 28, 
        description: "",
        image: "../../assets/images/EARRINGS/Butterfly Earrings/butterfly_1.jpeg"},
      { id:12, 
        name: "Handmade Small Hoop With Ball Charm Earrings, 24k Gold Charms · Personalized Gift", 
        price: 24, 
        description: "",
        image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
      { id:13, 
        name: "Handmade Freshwater Pearl Dangle Earrings, Removable Chain, 18k Gold Chain · Personalized Gift", 
        price: 30, 
        description: "",
        image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
      { id:14, 
        name: "Handmade Gold Saturn With/without Pearl Earrings, 18k/24k Gold Charms · Personalized Gift", 
        price:28, 
        description: "",
        image: "../../assets/images/EARRINGS/Saturn Earrings/saturn_1.jpeg"},  
      { id:15, 
        name: "Handmade Shooting Star Earrings, 24k Gold Charms · Personalized Gift", 
        price:28, 
        description: "",
        image: "../../assets/images/EARRINGS/Star Earrings/star_1.jpeg"},



  ]