export const products = [
        /* Necklaces: Id: 1-7
         Earrings: Id: 8-13 */
      { id: 1, 
        name: "Circle Pendant", 
        price: 42, 
        description: "14mm charm, 27mm chain",
        image: "../../assets/images/NECKLACES/Circle Pendant/circle_1.jpeg"},
      { id:2, 
        name: "Bar Pendant", 
        price:44, 
        description: " 5mm width, 22 inches length/customizable",
        image: "../../assets/images/NECKLACES/Bar Pendant/bar_1.jpeg"},
      { id:3, 
        name: "Lock Pendant", 
        price:48, 
        description: "Customizable up to 4 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Lock Pendant/lock_1.jpeg"},
      { id:4, 
        name: "Unisex Drip Chain", 
        price:45, 
        description: "Customizable up to 6 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Unisex Drip Chain/chain_1.jpeg"},
      { id:5, 
        name: "Heart Pendant", 
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Heart Pendant/heart_1.jpeg"},
      { id:6, 
        name: "Mini Circle Pendant", 
        price:45, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Mini Circle Pendants/minicircle_1.jpeg"},      
      { id:7, 
        name: "Gold Coin Chain Choker", 
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: ""},


      ]