export const products = [
    /* Necklaces: Id: 1-8 */
    { id: 1, 
        name: "Handmade and Customizable Circle Pendant Necklace, 18k Gold-Filled · Personalized Gift", 
        price: 42, 
        description: "14mm charm, 27mm chain",
        image: "../../assets/images/NECKLACES/Circle Pendant/circle_1.jpeg"},
    { id:2, 
        name: "Handmade and Customizable Bar Pendant Necklace, 18k Gold-Filled · Personalized Gift", 
        price:44, 
        description: " 5mm width, 22 inches length/customizable",
        image: "../../assets/images/NECKLACES/Bar Pendant/bar_1.jpeg"},
    { id:3, 
        name: "Handmade and Customizable Lock Pendant Necklace, 24k Gold-Filled · Personalized Gift", 
        price:48, 
        description: "Customizable up to 4 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Lock Pendant/lock_1.jpeg"},
    { id:4, 
        name: "Handmade and Customizable Heart Pendant Necklace, 24k Shiny Gold · Personalized Gift", 
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Heart Pendant/heart_1.jpeg"},
    { id:5, 
        name: "Handmade and Customizable Mini Circle Pendant Necklace, 18k Gold-Filled · Personalized Gift", 
        price:45, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Mini Circle Pendants/minicircle_1.jpeg"},
    { id:6, 
        name: "Unisex Handmade Drip Chain Necklace, Customizable Length, 24K Shiny Gold Chain · Personalized GiftDrip Chain", 
        price:45, 
        description: "Customizable up to 6 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Unisex Drip Chain/chain_1.jpeg"},
    { id:7, 
        name: "Handmade Gold Coin Necklace, Customizable Length, 24K Shiny Gold Chain · Personalized Gift", 
        price:42, 
        description: "Customizable up to 2 letters, available in uppercase and lowercase letters",
        image: "../../assets/images/NECKLACES/Mini Circle Pendants/minicircle_3.jpeg"},
  /*
    { id: 8,
        name: "Handmade Circle Butterfly Pendant Necklace, 18k Gold-Filled · Personalized Gift",
        price:42,
        description: "A butterfly necklace to remind yourself that you will soar when you are unapologetically you!",
        image: ""},
    /*
    { id: 9,
        name: "Handmade Handmade Circle Sun Pendant Necklace, 18k Gold-Filled · Personalized Gift",
        price:42,
        description: "A butterfly necklace to remind yourself that you will soar when you are unapologetically you!",
        image: ""},
    
    /* Earrings: Id: 9-15 */
      { id:10, 
        name: "Handmade Dangle Earrings With Ball Charms Earrings, 24k Gold Charms · Personalized Gift", 
        price: 27, 
        description: "",
        image: "../../assets/images/EARRINGS/Dangle Earrings with Ball Charm/dangle_1.jpeg"},
      { id:11, 
        name: "Handmade Gold Closed Circle Charm Earrings, 24k Gold Charms · Personalized Gift", 
        price: 27, 
        description: "",
        image: "../../assets/images/EARRINGS/Gold Round Charm/goldroundcharm_1.jpeg"},
      { id:12, 
        name: "Handmade Butterfly Charm Earrings, 18k Gold Charms · Personalized Gift", 
        price: 28, 
        description: "",
        image: "../../assets/images/EARRINGS/Butterfly Earrings/butterfly_1.jpeg"},
      { id:13, 
        name: "Handmade Small Hoop With Ball Charm Earrings, 24k Gold Charms · Personalized Gift", 
        price: 24, 
        description: "",
        image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
      { id:14, 
        name: "Handmade Freshwater Pearl Dangle Earrings, Removable Chain, 18k Gold Chain · Personalized Gift", 
        price: 30, 
        description: "",
        image: "../../assets/images/EARRINGS/Freshwater Pearl/freshwater_1.jpeg"},
      { id:15, 
        name: "Handmade Gold Saturn With/without Pearl Earrings, 18k/24k Gold Charms · Personalized Gift", 
        price:28, 
        description: "",
        image: "../../assets/images/EARRINGS/Saturn Earrings/saturn_1.jpeg"},  
      { id:16, 
        name: "Handmade Shooting Star Earrings, 24k Gold Charms · Personalized Gift", 
        price:28, 
        description: "",
        image: "../../assets/images/EARRINGS/Star Earrings/star_1.jpeg"},



  ]